version: '3.7'
services:
  oauth_sso_service:
    container_name: oauth_sso_service
    #指定构建的Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
      #工作目录空间
    working_dir: /go/src/github.com/OauthSSO/service
    volumes:
      - ./:/go/src/github.com/OauthSSO/service
    command: /bin/bash -c "go mod dowload && go build -o sso  main.go && ./sso"
    #设置环境变量
    environment:
      - GIN_MODE=release
      - GOPROXY=https://mirrors.aliyun.com/goproxy/
    ports:
      - "8084:8084"