version: '3'
services:
  oauthsso_web:
    container_name: oauthsso_web
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
      - ./dist:/app/dist
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run build
